//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_EF_MVVM
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Book
    {
        public int BookId { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
